/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import java.awt.*;
import javax.swing.*;
import BDD.conexion;
/**
 *
 * @author Andre
 */
public class ProductoPanel extends javax.swing.JPanel {
    private conexion con;
    /**
     * Creates new form ProductoPanel
     */
    public ProductoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void misComponentes(){
//        jlblNomProd;
//        jlblPrecio;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        jPFoto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPDetalles = new javax.swing.JPanel();
        jpDet = new javax.swing.JPanel();
        jlblNomProd = new javax.swing.JLabel();
        jlblPrecio = new javax.swing.JLabel();
        jpCarrito = new javax.swing.JPanel();
        lblBtnCarrito = new javax.swing.JLabel();

        Bg.setBackground(new java.awt.Color(255, 255, 255));
        Bg.setForeground(new java.awt.Color(255, 255, 255));
        Bg.setLayout(new java.awt.BorderLayout());

        jPFoto.setBackground(new java.awt.Color(255, 255, 255));
        jPFoto.setLayout(new java.awt.GridLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jPFoto.add(jLabel1);

        Bg.add(jPFoto, java.awt.BorderLayout.CENTER);

        jlblNomProd.setText("_____________________");

        jlblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblPrecio.setText("_____________________");

        javax.swing.GroupLayout jpDetLayout = new javax.swing.GroupLayout(jpDet);
        jpDet.setLayout(jpDetLayout);
        jpDetLayout.setHorizontalGroup(
            jpDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlblNomProd, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );
        jpDetLayout.setVerticalGroup(
            jpDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblNomProd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblBtnCarrito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconCarrito.png"))); // NOI18N
        lblBtnCarrito.setToolTipText("");
        lblBtnCarrito.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        lblBtnCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        lblBtnCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnCarritoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBtnCarritoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jpCarritoLayout = new javax.swing.GroupLayout(jpCarrito);
        jpCarrito.setLayout(jpCarritoLayout);
        jpCarritoLayout.setHorizontalGroup(
            jpCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCarritoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBtnCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpCarritoLayout.setVerticalGroup(
            jpCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCarritoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblBtnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPDetallesLayout = new javax.swing.GroupLayout(jPDetalles);
        jPDetalles.setLayout(jPDetallesLayout);
        jPDetallesLayout.setHorizontalGroup(
            jPDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDetallesLayout.createSequentialGroup()
                .addComponent(jpDet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPDetallesLayout.setVerticalGroup(
            jPDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDetallesLayout.createSequentialGroup()
                .addComponent(jpDet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jpCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Bg.add(jPDetalles, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnCarritoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnCarritoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBtnCarritoMouseReleased

    private void lblBtnCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnCarritoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBtnCarritoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPDetalles;
    private javax.swing.JPanel jPFoto;
    private javax.swing.JLabel jlblNomProd;
    private javax.swing.JLabel jlblPrecio;
    private javax.swing.JPanel jpCarrito;
    private javax.swing.JPanel jpDet;
    private javax.swing.JLabel lblBtnCarrito;
    // End of variables declaration//GEN-END:variables
}
